sonar.projectKey=employee-3-tier-project
sonar.projectName=Employee 3-Tier Project
sonar.sources=frontend/src,backend/src,database,nginx
sonar.exclusions=node_modules/**,frontend/dist/**,coverage/**,terraform/.terraform/**
sonar.tests=.
sonar.test.inclusions=**/*.test.js,**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
